version: '3.8'

services:
    postgresql-master:
        container_name: postgres-db-master
        image: postgres:alpine
        volumes:
            - /path/to/postgresql-persistence:/bitnami/postgresql
        ports:
            - "5435:5432"
        environment:
            - POSTGRES_PASSWORD=password-master

    postgresql-slave:
        container_name: postgres-db-replica
        image: postgres:alpine
        ports:
            - "5434:5432"
        volumes:
            - ./postgresql-slave:/bitnami/postgresql
        environment:
            POSTGRES_PASSWORD=password-replica

# volumes:
#     postgres-db: 
#         external: true